# https://cloud.google.com/appengine/docs/standard/python/config/appref

# application: arroba-pds

runtime: python39

# need only one instance so that new commits can be delivered to subscribeRepos
# subscribers in memory
automatic_scaling:
  min_instances: 1
  max_instances: 1

inbound_services:
  - warmup

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
# Will probably need to add -k eventlet once I switch to Flex and start serving
# websockets, but that crashes on Standard.
entrypoint: gunicorn --workers 1 --threads 10 --timeout 60 -b :$PORT app:app

handlers:

# dynamic
- url: .*
  script: auto
  secure: always
